const $=s=>document.querySelector(s); let queue=[],index=0,current=null,ruleBook=null;
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const j=await r.json();if(!r.ok||j.ok===false){const e=new Error(j.error||'请求失败');e.data=j;e.status=r.status;throw e}return j}
function notice(t,err=false){const e=$('#notice');e.textContent=t;e.className=`notice show${err?' error':''}`;setTimeout(()=>e.classList.remove('show'),3500)}
function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}
async function init(){ruleBook=(await api('/api/rules')); $('#bucket').innerHTML='<option value="">待人工判断</option>'+Object.entries(ruleBook.buckets).map(([id,b])=>`<option value="${id}">${id} ${b.name}</option>`).join(''); $('#bucket').onchange=fillUnits; queue=(await api('/api/candidates?status=WAITING_REVIEW&limit=500')).items; const q=new URLSearchParams(location.search).get('id'); if(q){const i=queue.findIndex(x=>String(x.id)===q);if(i>=0)index=i} await show();}
function fillUnits(selected=''){const b=$('#bucket').value;$('#unit').innerHTML='<option value="">待人工判断</option>'+Object.entries(ruleBook.units).filter(([id])=>!b||id.startsWith(b+'.')).map(([id,u])=>`<option value="${id}">${id} ${u.name}${u.requires_confirmation?' ⚠':''}</option>`).join('');$('#unit').value=selected;}
async function show(){if(!queue.length){current=null;$('#video').hidden=true;$('#video-empty').hidden=false;$('#queue-meta').textContent='没有待审核候选';$('#rules').innerHTML='<div class="empty">已处理完毕</div>';return} index=Math.max(0,Math.min(index,queue.length-1)); const d=await api(`/api/candidates/${queue[index].id}`);current=d.item;$('#video-empty').hidden=true;const v=$('#video');v.hidden=false;v.onerror=()=>notice('代理视频无法播放，请返回生产台重新下载代理。',true);v.src=`/media/candidate/${current.id}?v=${Date.now()}`;v.onloadedmetadata=()=>{if(!v.videoWidth||!v.videoHeight){notice('代理文件没有视频画面，请返回生产台重新下载代理。',true);return}v.currentTime=current.start_time};v.ontimeupdate=()=>{if(v.currentTime>=current.end_time){v.pause();v.currentTime=current.start_time}};$('#source-meta').innerHTML=`<a href="${esc(current.source_url)}" target="_blank" rel="noreferrer">${esc(current.source_title||current.source_url)}</a>`;$('#clip-time').textContent=`${current.start_time.toFixed(2)}s → ${current.end_time.toFixed(2)}s · ${current.duration.toFixed(2)}s`;$('#queue-meta').textContent=`${index+1} / ${queue.length} · 分数 ${Number(current.score).toFixed(0)}`;$('#bucket').value=current.candidate_bucket||'';fillUnits(current.candidate_unit||'');$('#viewpoint').value=current.candidate_viewpoint||'';$('#notes').value=''; renderRules(current.rules);}
function renderRules(items){$('#rules').innerHTML=items.map(r=>`<div class="rule" onclick="openRule('${r.rule_id}')"><strong>${r.rule_id}</strong><span class="badge ${r.status.toLowerCase()}">${r.status}</span><p>${esc(r.reason)}</p></div>`).join('');}
function openRule(id){const reason=(current.rules.find(x=>x.rule_id===id)||{}).reason||'';const r=ruleBook.redlines[id];const u=id==='UNIT'&&current?ruleBook.units[current.candidate_unit]:null;$('#drawer-title').textContent=r?`${id} · ${r.title}`:`${id} · 单元规则`;$('#drawer-body').innerHTML=r?`<p><span class="badge">PDF 第 ${r.page} 页</span></p><h3>PDF 原文</h3><div class="original">${esc(r.original)}</div><h3>系统解析</h3><p>硬规则：${r.hard?'是':'否'}<br>确定性检测：${r.deterministic||'无，默认人工判断'}</p><h3>当前依据</h3><div class="original">${esc(reason)}</div>`:`<h3>第四章详细规则</h3><div class="original">${esc(JSON.stringify(u,null,2))}</div><h3>当前依据</h3><p>${esc(reason)}</p>`;$('#drawer').classList.add('open')}
$('#close-drawer').onclick=()=>$('#drawer').classList.remove('open');
async function decide(decision,confirmHard=false){if(!current)return;const payload={decision,final_bucket:$('#bucket').value||null,final_unit:$('#unit').value||null,final_viewpoint:$('#viewpoint').value||null,notes:$('#notes').value,manual_rule_overrides:{},confirm_hard_fail:confirmHard};try{await api(`/api/candidates/${current.id}/review`,{method:'POST',body:JSON.stringify(payload)});if(decision!=='RESTORE'){queue.splice(index,1);if(index>=queue.length)index=Math.max(0,queue.length-1);notice(decision==='ACCEPT'?'已接受，等待最终源处理。':'已拒绝。');await show()}else{current.candidate_bucket=payload.final_bucket;current.candidate_unit=payload.final_unit;current.candidate_viewpoint=payload.final_viewpoint;notice('标签已保存，候选仍在审核队列。')}}catch(e){if(e.status===409&&e.data.requires_confirmation){const msg=e.data.hard_failures.map(x=>`${x.rule_id}: ${x.reason}`).join('\n');if(confirm(`该视频存在确定硬规则失败：\n${msg}\n\n确定仍然保留？`))return decide(decision,true)}notice(e.message,true)}}
async function saveLabels(){if(!current)return;await decide('RESTORE');notice('标签已保存，候选仍在审核队列。')}
$('#accept').onclick=()=>decide('ACCEPT');$('#reject').onclick=()=>decide('REJECT');$('#edit').onclick=saveLabels;$('#prev').onclick=()=>{index--;show()};$('#next').onclick=()=>{index++;show()};
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();const v=$('#video');v.paused?v.play():v.pause()}else if(e.key.toLowerCase()==='a')decide('ACCEPT');else if(e.key.toLowerCase()==='r')decide('REJECT');else if(e.key.toLowerCase()==='e')saveLabels();else if(e.key==='ArrowLeft'){index--;show()}else if(e.key==='ArrowRight'){index++;show()}});
init().catch(e=>notice(e.message,true));
